account:
  uin: 2375581742
  password: ''
  encrypt: false
  status: 0
  relogin:
    delay: 3
    interval: 3
    max-times: 0
  use-sso-address: true
heartbeat:
  interval: 5
message:
  post-format: string
  ignore-invalid-cqcode: false
  force-fragment: false
  fix-url: false
  proxy-rewrite: ''
  report-self-message: false
  remove-reply-at: false
  extra-reply-data: false
  skip-mime-scan: false
output:
  log-level: warn
  log-aging: 15
  log-force-new: true
  log-colorful: true
  debug: false
default-middlewares:
  access-token: ''
  filter: ''
  rate-limit: &ref_0
    enabled: false
    frequency: 1
    bucket: 1
database:
  leveldb:
    enable: true
  cache:
    image: data/image.db
    video: data/video.db
servers:
  - ws:
      host: 127.0.0.1
      port: 6700
      middlewares:
        access-token: ''
        filter: ''
        rate-limit: *ref_0

