port: 8080
allowWrite: true

plugins:
  ./src/ping:
  adapter-onebot:
    protocol: 'ws'
    selfId: '2375581742'
    endpoint: 'ws://127.0.0.1:6700'
  console:
  # dataview:
  insight:
  logger:
  manager:
  status:
